apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp-db
spec:
  serviceName: "myapp-db"
  replicas: 1
  selector:
    matchLabels:
      app: myapp-db
  template:
    metadata:
      labels:
        app: myapp-db
    spec:
      containers:
        - name: myapp-db
          image: postgres:15.10
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "myapp"
          ports:
            - containerPort: 5432